<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

<%@ include file="/views/common/adminHeader.jsp" %>

	<style>
       #test_btn1{
            /* margin-right:-4px; */
        }
        #btn_group button{
            border: 1px solid skyblue;
            background-color: rgba(0,0,0,0);
            color: skyblue;
            padding: 5px;
        }
        #btn_group button:hover{
            color:white;
            background-color: cornflowerblue;
        }
    </style>

		<div id="layoutSidenav_content">
		                <main>
		                    <div class="container-fluid px-4">
		                        <h1 class="mt-4">회원 관리</h1>
		                        <ol class="breadcrumb mb-4">
		                            <li class="breadcrumb-item active">전체 회원을 관리합니다.</li>
		                        </ol>
		                        <hr class="one">
                        		<div id="btn_group">
                       	 		<p>선택된 회원을 <button id="test_btn1">탈퇴</button> 처리 합니다. </p>
                        		</div>
                        		<hr class="one">
		
		
		
		                        <div class="row">
		                            
		                            <div class="card-body">
		                                <table id="datatablesSimple">
		                                    <thead>
		                                        <tr>
		                                            <th></th>
		                                            <th>번호</th>
		                                            <th>아이디</th>
		                                            <th>이름</th>
		                                            <th>닉네임</th>
		                                            <th>이메일</th>
		                                            <th>전화번호</th>
		                                            <th>주소</th>
		                                        </tr>
		                                    </thead>
		                                    <tfoot>
		                                        <tr>
		                                            <th></th>
		                                            <th>번호</th>
		                                            <th>아이디</th>
		                                            <th>이름</th>
		                                            <th>닉네임</th>
		                                            <th>이메일</th>
		                                            <th>전화번호</th>
		                                            <th>주소</th>
		                                        </tr>
		                                    </tfoot>
		                                    <tbody>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td>1</td>
		                                            <td>admin</td>
		                                            <td>관리자</td>
		                                            <td>예시용도</td>
		                                            <td>admin@운동행.com</td>
		                                            <td>01012345678</td>
		                                            <td>(08505) 서울특별시 금천구 가산디지털2로 115
		                                                (가산동, 대륭테크노타운3차) 811호</td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <th><input type="checkbox" name="checkall" id="checkall"></th>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                        <tr>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                            <td></td>
		                                        </tr>
		                                    </tbody>
		                                </table>
		                            </div>
		                        </div>
		                    </div>
		                    
		                </main>
		            </div>
		        </div>